### ISSUE TITLE
Error on  'ADMITTIME'

### ISSUE THREAD

**Issue by HodaMemar** [sajaddarabi/TAPER-EHR#6]
Hello Dr. Darabi
I try to run gen_data_df.py on Colab and upload the MIMIC III dataset (CSV files) folder on Google Drive. 
I get an error on ADMITTIME.

NumExpr defaulting to 2 threads.
removing diagnosis codes occuring less than 5 times. 
 num codes before filter: 88 after filtering: 1
removing cpt procedure codes occuring less than 5 times. 
 num codes before filter: 18 after filtering: 3
removing prescription codes occuring less than 5 times. 
 num codes before filter: 121 after filtering: 9
removing procedure codes occuring less than 5 times. 
 num codes before filter: 1995 after filtering: 1055
Traceback (most recent call last):
  File "/content/TAPER-EHR/TAPER-EHR/gen_data_df.py", line 99, in <module>
    df_adm_notes['ADMITTIME_C'] = df_adm_notes.ADMITTIME.apply(lambda x: str(x).split(' ')[0])
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ADMITTIME'
![TAPER](https://user-images.githubusercontent.com/66674325/97854653-01645680-1d0f-11eb-8425-a01348552778.png)

Could you please guide in this issue?
Thank you

**Comment by sajaddarabi** [comment]
Hello!

I can't seem to reproduce your error. I believe this may happen if you filter out all patients and you're left with an empty dataframe. Could you step into the code and make sure this is not the case?

**Comment by HodaMemar** [comment]
Hello

Thank you for your response.
